flags:
  react-haskell:
    ghcjs: false
  material-ui:
    ghcjs: false
packages:
- material-ui/
- pigment/
- react-haskell/
- react-haskell/example/simple/
- react-haskell/example/todomvc/
extra-deps:
- ghcjs-dom-0.1.1.3
- lens-family-1.2.0
- recursion-schemes-4.1.2
resolver: lts-2.15
